branches:
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
bundler_args: --without development

rvm:
- 1.9.3
- 2.0.0
- 2.1.5
- 2.2.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.2"
    - PUPPET_GEM_VERSION="~> 3.7"

